backend:
  name: git-gateway
  branch: main # или master, проверь свою основную ветку

media_folder: "src/img"
public_folder: "img"

collections:
  - name: "content"
    label: "Контент"
    files:
      - label: "Главная страница"
        name: "home"
        file: "src/data/content.json"
        fields:
          - { label: "Заголовок Hero", name: "hero_title", widget: "string" }
          - { label: "Текст Hero", name: "hero_text", widget: "text" }
          - { label: "О нас - Заголовок", name: "about_title", widget: "string" }
          - { label: "О нас - Текст", name: "about_text", widget: "markdown" }
